title: im seoin
baseurl: "/" 
url: "https://inseo24.github.io"

# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-seo-tag

permalink: pretty

search_enabled: true

aux_links:
  "seoin's GitHub":
    - "//github.com/inseo24"

aux_links_new_tab: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true
nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "위로"

color_scheme: nil

ga_tracking: UA-2709176-10
ga_tracking_anonymize_ip: true 

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
collections:
  about:
    permalink: "/:collection/:path/"
    output: true
  java:
    permalink: "/:collection/:path/"
    output: true
  kotlin:
    permalink: "/:collection/:path/"
    output: true
  etc:
    permalink: "/:collection/:path/"
    output: true

  
just_the_docs:
  collections:
    about:
      name: about
    java:
      name: java
    kotlin:
      name: kotlin
    etc:
      name: etc
